import asyncio
from app.database import SessionLocal
from app.services.affirmation_service import get_or_create_daily_affirmation

async def test():
    db = SessionLocal()
    try:
        aff = await get_or_create_daily_affirmation(db)
        print(f"Affirmation: {aff.affirmation_text}")
        print(f"Date: {aff.affirmation_date}")
        print(f"Generated By: {aff.generated_by}")
    finally:
        db.close()

if __name__ == "__main__":
    asyncio.run(test())
