"""add_indexes

Revision ID: 15b8895c9f85
Revises: 1918d005a310
Create Date: 2026-06-15 02:38:21.300743
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '15b8895c9f85'
down_revision: Union[str, None] = '1918d005a310'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_moods_user_id'), 'moods', ['user_id'], unique=False)
    op.create_index(op.f('ix_reflection_sessions_separation_id'), 'reflection_sessions', ['separation_id'], unique=False)
    op.create_index(op.f('ix_reflection_sessions_user_id'), 'reflection_sessions', ['user_id'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reflection_sessions_user_id'), table_name='reflection_sessions')
    op.drop_index(op.f('ix_reflection_sessions_separation_id'), table_name='reflection_sessions')
    op.drop_index(op.f('ix_moods_user_id'), table_name='moods')
    # ### end Alembic commands ###
