"""add_is_viewed_to_user_daily_insights

Revision ID: 1918d005a310
Revises: 6e2419ee0084
Create Date: 2026-06-13 17:35:48.111258
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '1918d005a310'
down_revision: Union[str, None] = '6e2419ee0084'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('relationships', 'summary_insight',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    # Add is_viewed as nullable first so existing rows aren't rejected
    op.add_column('user_daily_insights', sa.Column('is_viewed', sa.Boolean(), nullable=True))
    op.add_column('user_daily_insights', sa.Column('viewed_at', sa.DateTime(timezone=True), nullable=True))
    # Backfill all existing rows with False (they were never viewed via the new flow)
    op.execute("UPDATE user_daily_insights SET is_viewed = FALSE WHERE is_viewed IS NULL")
    # Now enforce NOT NULL
    op.alter_column('user_daily_insights', 'is_viewed', nullable=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_daily_insights', 'viewed_at')
    op.drop_column('user_daily_insights', 'is_viewed')
    op.alter_column('relationships', 'summary_insight',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    # ### end Alembic commands ###
