"""add relationship history

Revision ID: 6e2419ee0084
Revises: 22ba7caeeeaf
Create Date: 2026-06-08 18:10:23.046993
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '6e2419ee0084'
down_revision: Union[str, None] = '22ba7caeeeaf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('relationships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user1_id', sa.Integer(), nullable=False),
    sa.Column('user2_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('journey_score', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user1_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user2_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_relationships_id'), 'relationships', ['id'], unique=False)
    op.add_column('letters', sa.Column('relationship_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'letters', 'relationships', ['relationship_id'], ['id'], ondelete='CASCADE')
    op.add_column('separations', sa.Column('relationship_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'separations', 'relationships', ['relationship_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'separations', type_='foreignkey')
    op.drop_column('separations', 'relationship_id')
    op.drop_constraint(None, 'letters', type_='foreignkey')
    op.drop_column('letters', 'relationship_id')
    op.drop_index(op.f('ix_relationships_id'), table_name='relationships')
    op.drop_table('relationships')
    # ### end Alembic commands ###
