"""Add drift bottle tables

Revision ID: 9f5e6e3eef2b
Revises: 15b8895c9f85
Create Date: 2026-06-22 14:28:22.289548
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '9f5e6e3eef2b'
down_revision: Union[str, None] = '15b8895c9f85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drift_bottle_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('reward_type', sa.String(), nullable=False),
    sa.Column('reward_value', sa.Integer(), nullable=False),
    sa.Column('opened_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_drift_bottle_history_id'), 'drift_bottle_history', ['id'], unique=False)
    op.create_index(op.f('ix_drift_bottle_history_opened_at'), 'drift_bottle_history', ['opened_at'], unique=False)
    op.create_index(op.f('ix_drift_bottle_history_user_id'), 'drift_bottle_history', ['user_id'], unique=False)
    op.create_table('user_rewards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('love_tokens', sa.Integer(), nullable=True),
    sa.Column('aura_fragments', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_rewards_id'), 'user_rewards', ['id'], unique=False)
    op.create_index(op.f('ix_user_rewards_user_id'), 'user_rewards', ['user_id'], unique=True)
    op.drop_index(op.f('ix_apscheduler_jobs_next_run_time'), table_name='apscheduler_jobs')
    op.drop_table('apscheduler_jobs')
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('apscheduler_jobs',
    sa.Column('id', sa.VARCHAR(length=191), autoincrement=False, nullable=False),
    sa.Column('next_run_time', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('job_state', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('apscheduler_jobs_pkey'))
    )
    op.create_index(op.f('ix_apscheduler_jobs_next_run_time'), 'apscheduler_jobs', ['next_run_time'], unique=False)
    op.drop_index(op.f('ix_user_rewards_user_id'), table_name='user_rewards')
    op.drop_index(op.f('ix_user_rewards_id'), table_name='user_rewards')
    op.drop_table('user_rewards')
    op.drop_index(op.f('ix_drift_bottle_history_user_id'), table_name='drift_bottle_history')
    op.drop_index(op.f('ix_drift_bottle_history_opened_at'), table_name='drift_bottle_history')
    op.drop_index(op.f('ix_drift_bottle_history_id'), table_name='drift_bottle_history')
    op.drop_table('drift_bottle_history')
    # ### end Alembic commands ###
